name: Latest blog post workflow
on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.jasonandersen.xyz/rss" # Replace with your RSS feed URL
          max_post_count: 3
          readme_path: README.md